#!/usr/bin/env bash
# =================================================================
# Generate a production release keystore for signing the APK.
# =================================================================
# Output: android/qtbm-release.keystore
# Also writes android/keystore.properties (git-ignored).
# =================================================================
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

KEYSTORE_FILE="$PROJECT_ROOT/android/app/qtbm-release.keystore"
PROPS_FILE="$PROJECT_ROOT/android/keystore.properties"

echo "============================================================"
echo " QTBM CRYPTO — Release Keystore Generator"
echo "============================================================"
echo ""

if [[ -f "$KEYSTORE_FILE" ]]; then
  read -rp "Keystore already exists at $KEYSTORE_FILE. Overwrite? [y/N] " yn
  case "$yn" in
    [Yy]*) rm -f "$KEYSTORE_FILE" "$PROPS_FILE" ;;
    *) echo "Aborted."; exit 0 ;;
  esac
fi

read -rp "Keystore password (min 6 chars): " -s STORE_PASS; echo
if [[ ${#STORE_PASS} -lt 6 ]]; then
  echo "✗ Password too short (minimum 6 characters)." >&2
  exit 1
fi
read -rp "Confirm keystore password: " -s STORE_PASS_CONFIRM; echo
if [[ "$STORE_PASS" != "$STORE_PASS_CONFIRM" ]]; then
  echo "✗ Passwords do not match." >&2
  exit 1
fi

read -rp "Key password (Enter to reuse keystore password): " -s KEY_PASS; echo
KEY_PASS="${KEY_PASS:-$STORE_PASS}"

if [[ "$KEY_PASS" != "$STORE_PASS" ]]; then
  echo "⚠ PKCS12 keystores require the SAME password for store and key."
  echo "  The -keypass value will be ignored; using the store password for both."
  KEY_PASS="$STORE_PASS"
fi

read -rp "Key alias [qtbm]: " ALIAS
ALIAS="${ALIAS:-qtbm}"

read -rp "Your name or organization [QTBM CRYPTO]: " CN
CN="${CN:-QTBM CRYPTO}"

read -rp "Country code (2 letters) [YE]: " COUNTRY
COUNTRY="${COUNTRY:-YE}"

echo ""
echo "▶ Generating keystore…"
keytool -genkeypair -v \
  -storetype PKCS12 \
  -keystore "$KEYSTORE_FILE" \
  -alias "$ALIAS" \
  -keyalg RSA -keysize 4096 \
  -sigalg SHA256withRSA \
  -validity 10950 \
  -storepass "$STORE_PASS" \
  -keypass  "$KEY_PASS" \
  -dname "CN=${CN}, OU=Engineering, O=${CN}, L=Sanaa, ST=Sanaa, C=${COUNTRY}"

# Write keystore.properties (git-ignored)
cat > "$PROPS_FILE" <<EOF
# Auto-generated by scripts/generate-keystore.sh — DO NOT COMMIT.
storeFile=qtbm-release.keystore
storePassword=${STORE_PASS}
keyAlias=${ALIAS}
keyPassword=${KEY_PASS}
EOF
chmod 600 "$PROPS_FILE"

echo ""
echo "✓ Keystore created: $KEYSTORE_FILE"
echo "✓ Properties file: $PROPS_FILE"
echo ""
echo "  IMPORTANT:"
echo "  - Keep qtbm-release.keystore and keystore.properties SAFE."
echo "  - The same keystore MUST be used for every release update."
echo "  - If you lose it, you cannot publish updates to the same app listing."
echo ""
